apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSAuthPolicy
metadata:
  name: keycloak-model-access
  namespace: models-as-a-service
spec:
  modelRefs:
  - name: facebook-opt-125m-simulated
    namespace: llm
  subjects:
    groups:
    - name: tier-free-users
    - name: tier-premium-users
    - name: tier-enterprise-users
